/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {


    @Test
    void colorImageTest() throws IOException {
        App underTest=new App();
        Bitmap test=new Bitmap();
        BufferedImage result=test.colorImage(ImageIO.read(new File("C://Users/Computergy World/Desktop/bitmap.bmp")));
        assertNotNull(result);
    }


    @Test
    void thresholdImageTest() throws IOException {
        Bitmap test=new Bitmap();
        BufferedImage result=test.thresholdImage(ImageIO.read(new File("C://Users/Computergy World/Desktop/bitmap.bmp")),100);
        assertNotNull(result);

    }

    @Test
    void rotateTest() throws IOException {
        Bitmap test=new Bitmap();
        BufferedImage result=test.rotate(ImageIO.read(new File("C://Users/Computergy World/Desktop/bitmap.bmp")),180);
        assertNotNull(result);

    }

    @Test
    void testImgChanged1() throws IOException {
        BufferedImage testImg=ImageIO.read(new File("C://Users/Computergy World/Desktop/bitmap.bmp"));

        Bitmap test=new Bitmap();
        BufferedImage result=test.rotate(ImageIO.read(new File("C://Users/Computergy World/Desktop/bitmap.bmp")),180);
        assertNotEquals(result,testImg);
    }

}
